package nl.naturalis.ant.contrib;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.Task;

/**
 * Maintains and generates build numbers.
 * 
 * @author Ayco Holleman
 *
 */
public class GetBuildNumberTask extends Task {

	public GetBuildNumberTask()
	{
	}

	private String project;
	private String propname;

	@Override
	public void execute() throws BuildException
	{
		try {
			if (project == null) {
				project = getProject().getName();
				if (project == null) {
					throw new BuildException("Missing required attribute \"project\"");
				}
			}
			if (propname == null) {
				propname = "build.number";
			}
			int build = 0;
			Properties props = new Properties();
			File file = getBuildNumberPropertiesFile();
			if (file.exists()) {
				props.load(new FileInputStream(file));
				build = Integer.parseInt(props.getProperty(project, "0"));
			}
			props.setProperty(project, String.valueOf(++build));
			String comments = "Generated by " + getClass().getName() + "\nIf you "
					+ "delete this file, build numbers will be reset to 1\n"
					+ "for builds carried out on this machine!";
			FileOutputStream fos = new FileOutputStream(file);
			props.store(fos, comments);
			fos.close();
			getProject().setUserProperty(propname, String.valueOf(build));
		}
		catch (IOException e) {
			throw new BuildException(e);
		}
	}

	/**
	 * The name of the property through which the build number will become
	 * available in you ant build. Defaults to "build.number".
	 * 
	 * @param propname
	 */
	public void setPropname(String propname)
	{
		this.propname = propname;
	}

	/**
	 * The name of the project for which to generate a build number. This
	 * defaults to ${ant.project.name}. Note, however, that this property might
	 * not be set, or it may not be unique (for example if you have multiple
	 * projects named "common"). Therefore, to be on the safe side, it is best
	 * to always set this attribute.
	 * 
	 * @param project
	 */
	public void setProject(String project)
	{
		this.project = project;
	}

	private static File getBuildNumberPropertiesFile()
	{
		String file = "/.naturalis.buildno";
		String path = System.getProperty("user.home") + file;
		System.out.println(path);
		return new File(path);
	}

}
